version: "2"
engines:
  python:
    enabled: true
    config:
      max-line-length: 100
      complexity:
        max: 10
      rules:
        - "python/flake8"  # Checks for Python code style and errors
        - "python/pylint"  # Checks for logical errors and code quality
  java:
    enabled: true
    config:
      max-line-length: 100
      complexity:
        max: 10
      rules:
        - "java/checkstyle"  # Java coding style checker
        - "java/pmd"         # Detects potential bugs and issues in Java
        - "java/findbugs"    # Finds bugs in Java code
