version: "2"
engines:
  python/flake8:
    enabled: true
    config:
      max-line-length: 100
  python/pylint:
    enabled: true
    config:
      max-line-length: 100
  java/checkstyle:
    enabled: true
    config:
      max-line-length: 100
      complexity:
        max: 10
  java/pmd:
    enabled: true
    config:
      max-line-length: 100
      complexity:
        max: 10
  java/findbugs:
    enabled: true
    config:
      max-line-length: 100
      complexity:
        max: 10
